name: pybase
version: 0.0.0
homepage: https://github.com/morloc-project/
synopsis: Base types and functions for Python3
description: Lots of detail about all this
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-project/pybase
bug-reports: https://github.com/morloc-project/pybase
